name: robotlabExperiments
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy<2.0
  - scikit-learn=1.5.2
  - scipy
  - pandas
  - matplotlib
  - seaborn
  - toml
  - pip
  - pip:
    - pyyaml
    - git+https://github.com/AGardinon/ActiveLearningCLassiFier.git@4123b09886b75842ffd21b366686f169bfe20f6f
    - -e ./
